### ISSUE TITLE
host this on netlify of github-pages

### ISSUE THREAD

**Issue by gagangaur** [CassandraGoose/non-earthling-news#1]
hello, @CassandraGoose you should definitely host this on netlify or GitHub pages so the people coming up from the CJ's repo can actually see what you have built as you were the first person to submit the project this will definitely help others.

**Comment by CassandraGoose** [comment]
Sure, I'll go ahead and deploy what I have now!

**Comment by CassandraGoose** [comment]
Alright, I'm going to close this as I have deployed to https://non-earthling-news.surge.sh/. The readme now has the link as well!
